cameras:
  House-Back-Yard:
    url: rtsp://nvruser:NVRAccess@192.168.200.51:554/cam/realmonitor?channel=1&subtype=0
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
  House-Front-Door:
    url: rtsp://nvruser:NVRAccess@192.168.200.52/axis-media/media.amp
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
  Barn_SE_Corner:
    url: rtsp://nvruser:NVRAccess@192.168.200.53:554/Streaming/Channels/1/
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
  Garage-Right:
    url: rtsp://nvruser:NVRAccess@192.168.200.55:554/Streaming/Channels/101/
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
  Garage-Left:
    url: rtsp://nvruser:NVRAccess@192.168.200.56:554/Streaming/Channels/101/
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
  House-NE-Corner:
    url: rtsp://nvruser:NVRAccess@192.168.200.57:554/cam/realmonitor?channel=1&subtype=0
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
  Barn-Back:
    url: rtsp://nvruser:NVRAccess@192.168.200.58:554/cam/realmonitor?channel=1&subtype=0
    enabled: true
    schedules:
    - name: schedule_0
      frequency: hourly
      enabled: true
      value: 1
      time_window:
        start: 06:00
        end: '20:00'
    capture_settings:
      jpeg_quality: 90
      timeout_seconds: 10
      retry_count: 3
      retry_delay_seconds: 1.0
